name: Go

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
env:
  isNightly: ${{ contains(github.ref, 'dev') }}
  isReleaseCandidate: ${{ contains(github.ref, 'tags') && contains(github.ref, '-rc') }}
  isFinalRelease: ${{ contains(github.ref, 'tags') && !contains(github.ref, '-rc') }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out source code
      uses: actions/checkout@v2

    - name: Compile for ARM
      run: make cross

    # - name: Upload Build Artifacts
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: web-config-server
    #     path: dist/web-config-server

    - name: Update dev tag
      if: env.isNightly == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag : dev
        commit : dev
        allowUpdates: true
        replacesArtifacts: true
        prerelease: true
        artifacts: web-config-server

    # - name: Release (pre-release)
    #   if: env.isReleaseCandidate == 'true'
    #   uses: ncipollo/release-action@v1
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     prerelease: true
    #     artifacts: web-config-server
        
    - name: Update latest-rc tag
      if: env.isReleaseCandidate == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest-rc
        allowUpdates: true
        replacesArtifacts: true
        prerelease: true
        artifacts: web-config-server

    # - name: Release (final)
    #   if: env.isFinalRelease == 'true'
    #   uses: ncipollo/release-action@v1
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     artifacts: web-config-server
        
    - name: Update latest tag
      if: env.isFinalRelease == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        allowUpdates: true
        replacesArtifacts: true
        artifacts: web-config-server